model:
  name: 'MinkUNet18'
  in_feat_size: 1
  out_classes: 7

dataset:
  version: 'full'
  name: 'SyntheticKITTI'
  dataset_path: 'data/Synth4D'
  target_path: 'data/SemanticKITTI/data/sequences/'
  voxel_size: 0.05
  num_pts: 50000
  ignore_label: -1
  validate_target: false
  augment_data: true
  mapping_path: '_resources/synthetic.yaml'


pipeline:
  epochs: 100
  gpus: [0]
  precision: 32
  loss: 'SoftDICELoss'
  seed: 1234
  save_dir: 'experiments/source/synthkitti'

  dataloader:
    batch_size: 20
    num_workers: 16

  optimizer:
    name: 'Adam'
    lr: 0.01
    scheduler: true

  scheduler:
    scheduler_name: 'ExponentialLR'

  lightning:
    check_val_every_n_epoch: 5
    clear_cache_int: 1
    resume_checkpoint: null
    val_check_interval: 1.0
    num_sanity_val_steps: 0


  wandb:
    run_name: 'SOURCE_SYNTHKITTI_SEG-PT1'
    project_name: 'amazing-project'
    entity_name: 'name'
    offline: false

